name: travenor
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9


  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true


  assets: 
    - assets/images/splashScreenIcon.svg
    - assets/images/onboardingscreenNew.svg
    - assets/images/onboard.jpg
    - assets/images/onboard2.jpg
    - assets/images/onboard3.jpg
    - assets/icons/facebook.jpg
    - assets/icons/insta.jpg
    - assets/icons/twitter.jpg
    - assets/homescreen/avatar.png
    - assets/homescreen/darma.png
    - assets/homescreen/user1.png
    - assets/homescreen/user2 .png
    - assets/homescreen/user3.png
    - assets/homescreen/niladiri .png
    - assets/homescreen/darma.png
    - assets/details/Home.png
    - assets/details/avatar1.png
    - assets/details/detailimage4.png
    - assets/details/detailimage3.png
    - assets/details/detailimage2.png
    - assets/details/detailimage1.png
    - assets/details/detailimage0.png
    - assets/view/view_background.png
    - assets/view/hotel_thumb.png
    - assets/view/lemon_thumb.png
    - assets/view/avatar4.png
    - assets/view/avatar5.png
    - assets/view/avatar6.png
    - assets/images/underline.png
    - assets/homescreen/niladiri.png
    - assets/homescreen/darmar.png
    - assets/homescreen/highreck.png
   
  fonts:
    - family: Comgeometr
      fonts:
        - asset: assets/fonts/Comgeometr.ttf

    - family: GillsSansMT
      fonts:
        - asset: assets/fonts/GillsSansMT.ttf

